<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BDcomponentes [
    <!ELEMENT BDcomponentes (componente)+>
    <!ELEMENT componente (nombre,(precio|precioiva),tipo+,medida)>
    <!ELEMENT nombre (#PCDATA)>

    <!ELEMENT precio (#PCDATA)>
    <!ELEMENT precioiva (#PCDATA)>
    <!ELEMENT tipo (#PCDATA)>
    <!ELEMENT medida (#PCDATA)>
]>
<BDcomponentes>
    <componente>
        <nombre></nombre>
        <precio></precio>
        <tipo></tipo>
        <medida></medida>
    </componente>

    <componente>
        <nombre></nombre>
        <precioiva></precioiva>
        <tipo></tipo>
        <medida></medida>
    </componente>
</BDcomponentes>