=== alvaro2812/lenguaje_de_marcas/26_de_oct/empresa.dtd
<!ELEMENT empresaDistanza (pedidos)+>
<!ELEMENT pedidos (sucursal)+>
<!ELEMENT sucursal (Direccion_Envio,trabajador,fecha_envio,
observaciones_pedido,plazo_revision,articulo)+>
<!ATTLIST sucursal codigo_pedido ID #REQUIRED>
<!ELEMENT Direccion_Envio (#PCDATA)>
<!ELEMENT trabajador (#PCDATA)>
<!ELEMENT fecha_envio (#PCDATA)>
<!ELEMENT observaciones_pedido (#PCDATA)>
<!ELEMENT plazo_revision (#PCDATA)>

<!ELEMENT articulo (unidades_vendidas,precio_unidad,observaciones_art)+>
<!ELEMENT unidades_vendidas (#PCDATA)>
<!ELEMENT precio_unidad (#PCDATA)>
<!ELEMENT observaciones_art (#PCDATA)>
<!ATTLIST articulo codigo_articulo ID #REQUIRED>

=== alvaro2812/lenguaje_de_marcas/26_de_oct/empresa_dtd.xml
<!DOCTYPE empresaDistanza  SYSTEM "empresa.dtd">
<empresaDistanza>
    <pedidos>


        <sucursal codigo_pedido="A2345679">
            <Direccion_Envio>calle algo 22 , Yecla Murcia</Direccion_Envio>
            <trabajador>Pablo</trabajador>
            <fecha_envio>2022-10-12</fecha_envio>
            <observaciones_pedido></observaciones_pedido>
            <plazo_revision>8 DIAS</plazo_revision> 
            <articulo codigo_articulo="AAA-123">
                <unidades_vendidas>12</unidades_vendidas>
                <precio_unidad>30</precio_unidad>
                <observaciones_art></observaciones_art>
            </articulo>
        </sucursal>




    </pedidos>
    
</empresaDistanza>
