=== alvaro2812/lenguaje_de_marcas/26_de_oct/empresa.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="empresaDistanza" type="empresaDistanza"/>

    <xs:complexType name="empresaDistanza">
        <xs:sequence>
            <xs:element name="pedidos" type="pedidos" maxOccurs="1" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="pedidos">
        <xs:sequence>
            <xs:element name="sucursal" type="sucursal" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="sucursal">
        <xs:sequence>
            <xs:element name="Direccion_Envio" type="xs:string"/>
            <xs:element name="trabajador" type="xs:string"/>
            <xs:element name="fecha_envio" type="xs:date"/>
            <xs:element name="observaciones_pedido" type="xs:string"/>
            <xs:element name="plazo_revision" type="xs:string"/>
            <xs:element name="articulo" type="articulo" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="codigo_pedido" type="TipoCodigo_Pedido" use="required"/>
    </xs:complexType>

<xs:simpleType name ="TipoCodigo_Pedido">
    <xs:restriction base ="xs:string">
        <xs:pattern value="[A-Za-z]([0-9]{7})"/>
    </xs:restriction>
</xs:simpleType>


    <xs:complexType name="articulo">
        <xs:sequence>
            <xs:element name="unidades_vendidas" type="xs:integer"/>
            <xs:element name="precio_unidad" type="xs:integer"/>
            <xs:element name="observaciones_art" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="codigo_articulo" type="Tipocodigo_articulo" use="required"/>
    </xs:complexType>

    <xs:simpleType name ="Tipocodigo_articulo">
    <xs:restriction base ="xs:string">
        <xs:pattern value="[A-Z]{3}-[0-9]{3}"/>
    </xs:restriction>
</xs:simpleType>

</xs:schema>

=== alvaro2812/lenguaje_de_marcas/26_de_oct/empresa.xml
<?xml version="1.0" encoding="UTF-8"?>
<empresaDistanza xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./empresa.xsd">
    <pedidos>


        <sucursal codigo_pedido="A2345679">
            <Direccion_Envio>calle algo 22 , Yecla Murcia</Direccion_Envio>
            <trabajador>Pablo</trabajador>
            <fecha_envio>2022-10-12</fecha_envio>
            <observaciones_pedido></observaciones_pedido>
            <plazo_revision></plazo_revision> 
            <articulo codigo_articulo="AAA-123">
                <unidades_vendidas>12</unidades_vendidas>
                <precio_unidad>30</precio_unidad>
                <observaciones_art></observaciones_art>
            </articulo>
        </sucursal>




    </pedidos>
    
</empresaDistanza>
